# https://taskfile.dev/
version: "3"

dotenv:
  - .env

tasks:
  install-flit:
    status:
      - which flit
    cmds:
      - python3 -m pip install flit

  install:
    deps:
      - install-flit
    sources:
      - pyproject.toml
    cmds:
      - python3 -m flit install --deps=production --symlink

  fetch:
    deps:
      - install
    generates:
      - stars.json
    cmds:
      - test $GITHUB_TOKEN
      - echo ${GITHUB_TOKEN:0:5}
      - >
        python3 -m ghstars fetch
        --token $GITHUB_TOKEN
        --orgs life4 orsinium-labs

  render:
    deps:
      - install
    cmds:
      - python3 -m ghstars render

  release:
    desc: generate and upload a new release
    deps:
      - install-flit
    cmds:
      - which gh
      - test {{.CLI_ARGS}}
      - cat ghstars/__init__.py | grep {{.CLI_ARGS}}
      - rm -rf dist/
      - flit build
      - flit publish
      - git tag {{.CLI_ARGS}}
      - git push
      - git push --tags
      - gh release create --generate-notes {{.CLI_ARGS}}
      - gh release upload {{.CLI_ARGS}} ./dist/*
