# https://taskfile.dev/
version: "3"

dotenv:
  - .env

tasks:
  install-flit:
    status:
      - which flit
    cmds:
      - python3 -m pip install flit

  install:
    deps:
      - install-flit
    sources:
      - pyproject.toml
    cmds:
      - python3 -m flit install --deps=production --symlink

  fetch:
    deps:
      - install
    generates:
      - stars.json
    cmds:
      - test $GITHUB_TOKEN
      - >
        python3 -m ghstars fetch
        --token $GITHUB_TOKEN
        --orgs life4 orsinium-labs

  render:
    deps:
      - install
    cmds:
      - python3 -m ghstars render
